# permissions for end users to edit dirfiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dirfile-editor-role
rules:
- apiGroups:
  - file.felinae98.cn
  resources:
  - dirfiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - file.felinae98.cn
  resources:
  - dirfiles/status
  verbs:
  - get
