# permissions for end users to view filekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filekeeper-viewer-role
rules:
- apiGroups:
  - file.felinae98.cn
  resources:
  - filekeepers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - file.felinae98.cn
  resources:
  - filekeepers/status
  verbs:
  - get
