# permissions for end users to edit filekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filekeeper-editor-role
rules:
- apiGroups:
  - file.felinae98.cn
  resources:
  - filekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - file.felinae98.cn
  resources:
  - filekeepers/status
  verbs:
  - get
