apiVersion: file.felinae98.cn/v1
kind: FileKeeper
metadata:
  name: filekeeper-sample
spec:
  dir: /tmp/a
  files:
    - file1
    - file4
status:
  exsitingFiles:
    k8s-node1:
    - file1
    - file2
